;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	end-of-buffer
	forward-sexp
	haml-electric-backspace
	keyboard-quit
	kill-region
	point-undo
	sp--self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	))
