(deftheme flatui
  "Created 2014-10-21.")

(custom-theme-set-variables
 'flatui
 '(ansi-color-names-vector ["#ecf0f1" "#e74c3c" "#2ecc71" "#f1c40f" "#2492db" "#9b59b6" "#1abc9c" "#2c3e50"]))

(custom-theme-set-faces
 'flatui
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#2492db" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#9b59b6" :underline t :weight normal))))
 '(cursor ((t (:foreground "#2c3e50" :background "#34495e"))))
 '(escape-glyph ((t (:foreground "#f1c40f" :bold t))))
 '(fringe ((t (:foreground "#34495e" :background "#dfe4ea"))))
 '(header-line ((t (:foreground "#16a085" :background "#34495e" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#1abc9c"))))
 '(success ((t (:foreground "#27ae60" :weight bold))))
 '(warning ((t (:foreground "#d35400" :weight bold))))
 '(compilation-info ((t (:foreground "#27ae60" :underline t))))
 '(compilation-line-number ((t (:foreground "#f1c40f"))))
 '(compilation-mode-line-exit ((t (:foreground "#1abc9c" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#c0392b" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#d98c10" :weight bold))))
 '(match ((t (:background "#1abc9c" :foreground "#34495e"))))
 '(isearch ((t (:foreground "#ecf0f1" :weight bold :background "#e74c3c"))))
 '(isearch-fail ((t (:foreground "#f1c40f" :weight bold :background "#c0392b"))))
 '(lazy-highlight ((t (:foreground "#34495e" :weight bold :background "#f1c40f"))))
 '(menu ((t (:foreground "#2c3e50" :background "#dfe4ea"))))
 '(minibuffer-prompt ((t (:foreground "#34495e" :weight bold))))
 '(region ((((class color) (min-colors 89)) (:background "#f1c40f" :foreground "#2c3e50")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#1abc9c"))))
 '(trailing-whitespace ((t (:background "#e74c3c"))))
 '(vertical-border ((t (:foreground "#dfe4ea"))))
 '(font-lock-builtin-face ((t (:foreground "#16a085"))))
 '(font-lock-comment-face ((t (:foreground "#7f8c8d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#95a5a6"))))
 '(font-lock-constant-face ((t (:foreground "#e67e22"))))
 '(font-lock-doc-face ((t (:foreground "#7f8c8d"))))
 '(font-lock-function-name-face ((t (:foreground "#34495e" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#d98c10"))))
 '(font-lock-negation-char-face ((t (:foreground "#2492db" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#e74c3c" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d98c10" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#9b59b6" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#0a74b9"))))
 '(font-lock-type-face ((t (:foreground "#2492db"))))
 '(font-lock-variable-name-face ((t (:foreground "#8e44ad"))))
 '(font-lock-warning-face ((t (:foreground "#d35400" :weight bold))))
 '(ace-jump-face-background ((t (:foreground "#27ae60" :background "#ecf0f1" :inverse-video nil))))
 '(ace-jump-face-foreground ((t (:foreground "#27ae60" :background "#ecf0f1" :inverse-video nil))))
 '(ac-candidate-face ((t (:background "#95a5a6" :foreground "#2c3e50"))))
 '(ac-selection-face ((t (:background "#7f8c8d" :foreground "#2c3e50"))))
 '(popup-tip-face ((t (:background "#f1c40f" :foreground "#2c3e50"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#7f8c8d"))))
 '(popup-scroll-bar-background-face ((t (:background "#dfe4ea"))))
 '(popup-isearch-match ((t (:background "#ecf0f1" :foreground "#2c3e50"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#27ae60" :background "#ecf0f1")) (t (:foreground "#27ae60" :background "#ecf0f1"))))
 '(diff-changed ((t (:foreground "#e67e22"))))
 '(diff-context ((t (:foreground "#95a5a6"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#e74c3c" :background "#ecf0f1")) (t (:foreground "#e74c3c" :background "#ecf0f1"))))
 '(diff-refine-added ((t :inherit diff-added :background "#2ecc71" :weight bold)))
 '(diff-refine-change ((t :inherit diff-changed :weight bold)))
 '(diff-refine-removed ((t :inherit diff-removed :background "#c0392b" :weight bold)))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#2c3e50" :weight bold)) (t (:foreground "#2c3e50" :weight bold))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#2c3e50" :weight bold)) (t (:foreground "#2c3e50" :weight bold))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#8e44ad" :weight bold)) (t (:foreground "#8e44ad" :weight bold))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#e74c3c") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#e74c3c" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#d98c10") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#d98c10" :weight bold :underline t))))
 '(guide-key/highlight-command-face ((t (:foreground "#2492db"))))
 '(guide-key/key-face ((t (:foreground "#d98c10"))))
 '(guide-key/prefix-command-face ((t (:foreground "#8e44ad"))))
 '(helm-action ((t (:underline nil))))
 '(helm-selection ((t (:background "#f1c40f" :underline nil :weight bold))))
 '(helm-candidate-number ((t (:foreground "#1abc9c"))))
 '(helm-source-header ((t (:foreground "#2c3e50" :weight bold))))
 '(helm-visible-mark ((t (:foreground "#e74c3c"))))
 '(helm-ff-directory ((t (:foreground "#2492db"))))
 '(helm-ff-executable ((t (:foreground "#d35400"))))
 '(helm-ff-symlink ((t (:foreground "#ecf0f1" :background "#9b59b6"))))
 '(helm-ff-prefix ((t (:foreground "#e74c3c"))))
 '(helm-M-x-key ((t (:foreground "#f1c40f"))))
 '(helm-grep-file ((t (:foreground "#1abc9c"))))
 '(helm-grep-lineno ((t (:foreground "#f1c40f"))))
 '(helm-grep-running ((t (:foreground "#e74c3c"))))
 '(helm-grep-finish ((t (:foreground "#1abc9c"))))
 '(helm-buffer-saved-out ((t (:foreground "#d98c10" :background nil))))
 '(helm-moccur-buffer ((t (:foreground "#f1c40f"))))
 '(ido-first-match ((t (:foreground "#d35400" :weight bold))))
 '(ido-only-match ((t (:foreground "#e67e22" :weight bold))))
 '(ido-subdir ((t (:foreground "#d98c10"))))
 '(ido-indicator ((t (:foreground "#f1c40f" :background "#d35400"))))
 '(magit-section-title ((t (:foreground "#2c3e50" :background nil :weight bold))))
 '(magit-branch ((t (:foreground "#2c3e50" :background "#1abc9c" :weight bold :box (:line-width 1 :color "#16a085")))))
 '(magit-item-highlight ((t (:background "#dfe4ea"))))
 '(magit-log-author ((t (:foreground "#0a74b9"))))
 '(magit-log-sha1 ((t (:foreground "#e67e22" :weight bold))))
 '(magit-tag ((t (:foreground "#8e44ad" :weight bold))))
 '(magit-log-head-label-head ((t (:foreground "#2c3e50" :background "#1abc9c" :weight bold :box (:line-width 1 :color "#16a085")))))
 '(magit-log-head-label-local ((t (:foreground "#2c3e50" :background "#1abc9c" :weight bold :box (:line-width 1 :color "#16a085")))))
 '(magit-log-head-label-default ((t (:foreground "#2c3e50" :background "#1abc9c" :weight bold :box (:line-width 1 :color "#16a085")))))
 '(magit-log-head-label-remote ((t (:foreground "#2c3e50" :background "#f1c40f" :weight bold :box (:line-width 1 :color "#d98c10")))))
 '(magit-log-head-label-tags ((t (:foreground "#8e44ad" :weight bold))))
 '(outline-1 ((t (:foreground "#16a085"))))
 '(outline-2 ((t (:foreground "#0a74b9"))))
 '(outline-3 ((t (:foreground "#8e44ad"))))
 '(outline-4 ((t (:foreground "#d98c10"))))
 '(outline-5 ((t (:foreground "#d35400"))))
 '(outline-6 ((t (:foreground "#c0392b"))))
 '(show-paren-mismatch ((t (:foreground "#f1c40f" :background "#c0392b" :weight bold))))
 '(show-paren-match ((t (:foreground "#ecf0f1" :background "#e74c3c" :weight bold))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#ecf0f1" :background "#2c3e50" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-inactive ((t (:foreground "#34495e" :background "#dfe4ea" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground "#e74c3c" :weight bold))))
 '(sml/global ((t (:foreground "#ecf0f1"))))
 '(sml/modes ((t (:foreground "#27ae60"))))
 '(sml/filename ((t (:foreground "#27ae60"))))
 '(sml/folder ((t (:foreground "#e67e22"))))
 '(sml/prefix ((t (:foreground "#e67e22"))))
 '(sml/read-only ((t (:foreground "#8e44ad"))))
 '(sml/modified ((t (:foreground "#d35400" :weight bold))))
 '(sml/outside-modified ((t (:background "#c0392b" :foreground "#f1c40f" :weight bold))))
 '(sml/line-number ((t (:foreground "#1abc9c" :weight bold))))
 '(sml/col-number ((t (:foreground "#1abc9c" :weight bold))))
 '(sml/vc ((t (:foreground "#2492db" :weight bold))))
 '(sml/vc-edited ((t (:foreground "#d35400" :weight bold))))
 '(sml/git ((t (:foreground "#2492db" :weight bold))))
 '(term-color-black ((t (:foreground "#2c3e50" :background "#2c3e50"))))
 '(term-color-red ((t (:foreground "#c0392b" :background "#c0392b"))))
 '(term-color-green ((t (:foreground "#27ae60" :background "#27ae60"))))
 '(term-color-yellow ((t (:foreground "#d98c10" :background "#d98c10"))))
 '(term-color-blue ((t (:foreground "#0a74b9" :background "#0a74b9"))))
 '(term-color-magenta ((t (:foreground "#8e44ad" :background "#8e44ad"))))
 '(term-color-cyan ((t (:foreground "#16a085" :background "#16a085"))))
 '(term-color-white ((t (:foreground "#ecf0f1" :background "#ecf0f1"))))
 '(web-mode-symbol-face ((t (:inherit font-lock-constant-face))))
 '(whitespace-space ((t (:background "#ecf0f1" :foreground "#f1c40f"))))
 '(whitespace-hspace ((t (:background "#ecf0f1" :foreground "#f1c40f"))))
 '(whitespace-tab ((t (:background "#e67e22"))))
 '(whitespace-newline ((t (:foreground "#f1c40f"))))
 '(whitespace-trailing ((t (:background "#e74c3c"))))
 '(whitespace-line ((t (:background nil :foreground "#e74c3c"))))
 '(whitespace-space-before-tab ((t (:background "#ecf0f1" :foreground "#e74c3c"))))
 '(whitespace-indentation ((t (:background "#ecf0f1" :foreground "#f1c40f"))))
 '(whitespace-empty ((t (:background "#d98c10"))))
 '(whitespace-space-after-tab ((t (:background "#ecf0f1" :foreground "#e74c3c"))))
 '(default ((t (:background "white" :foreground "#2c3e50")))))

(provide-theme 'flatui)
